version: 2.1
jobs:
  flutter_docter:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          name: Run Flutter Docter
          command: flutter doctor

  test:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          name: Run Flutter Test
          command: flutter test

workflows:
  build_and_test:
    jobs:
      - flutter_docter
      - test
